import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e5eeff",
        "surface-tint": "#585e6c",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed": "#e0e3e5",
        "background": "#f8f9ff",
        "on-error-container": "#93000a",
        "outline": "#76777c",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#ccdbf4",
        "tertiary-container": "#1d2122",
        "tertiary": "#06090b",
        "inverse-surface": "#223144",
        "on-primary-fixed": "#161c27",
        "on-tertiary-container": "#84888a",
        "on-tertiary-fixed": "#181c1e",
        "tertiary-fixed-dim": "#c3c7c9",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdcc3",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#603100",
        "on-background": "#0d1c2e",
        "surface-variant": "#d4e4fc",
        "on-primary-fixed-variant": "#414754",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d4e4fc",
        "primary-fixed": "#dde2f3",
        "error-container": "#ffdad6",
        "on-surface": "#0d1c2e",
        "secondary-container": "#fd8b00",
        "error": "#ba1a1a",
        "on-surface-variant": "#45474c",
        "surface-container-low": "#eff4ff",
        "outline-variant": "#c6c6cc",
        "on-secondary-fixed-variant": "#6e3900",
        "on-primary-container": "#828796",
        "on-tertiary-fixed-variant": "#434749",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#c1c6d7",
        "surface": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#1a202c",
        "inverse-primary": "#c1c6d7",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        primary: {
          DEFAULT: '#030813',
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316', 
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        secondary: {
          DEFAULT: '#904d00',
          900: '#0f0f0f',
          800: '#1a1a1a',
        }
      },
      fontFamily: {
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "xs": "4px",
        "md": "16px",
        "margin-desktop": "80px",
        "max-width": "1280px",
        "base": "4px",
        "lg": "24px",
        "xl": "48px",
        "sm": "8px"
      },
      borderRadius: {
        'lg': '0.65rem',
      },
      // Ajout des ombres manquantes pour réparer globals.css
      boxShadow: {
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
        'card-hover': '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
      }
    },
  },
  plugins: [],
};
export default config;