// Compiled version of seed.ts for Docker production environment
// Run with: node prisma/seed.js
import { PrismaClient, Role, ListingStatus, ListingType, PropertyType, PostStatus } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

function getBlogs(superAdminId) {
  return [
    {
      title: "Comment bien investir dans l'immobilier au Cameroun",
      slug: 'comment-bien-investir-immobilier',
      excerpt: "Le marché immobilier camerounais connaît une croissance fulgurante. Découvrez les clés pour réaliser un investissement rentable.",
      content: [
        "Le marché immobilier camerounais offre de nombreuses opportunités pour les investisseurs avertis. Voici les points essentiels à considérer :",
        "",
        "1. Choisir le bon emplacement",
        "Les quartiers en plein développement comme Bastos à Yaoundé ou Bonanjo à Douala offrent le meilleur potentiel de plus-value. Privilégiez les zones bénéficiant de nouvelles infrastructures (routes, écoles, centres commerciaux).",
        "",
        "2. Sécuriser le foncier",
        "Avant tout achat, vérifiez le titre foncier auprès du Conservatoire Foncier. Un titre foncier en règle est la garantie d'un investissement serein. Méfiez-vous des promesses de vente non authentifiées.",
        "",
        "3. Financer son projet",
        "Les banques camerounaises proposent des crédits immobiliers à des taux compétitifs (autour de 8-10% sur 15-20 ans). La Microfinance peut être une alternative pour les petits projets.",
        "",
        "4. Rentabilité locative",
        "Un bien bien situé à Yaoundé ou Douala peut générer un rendement locatif de 6 à 10% par an. Les studios et les appartements 2 pièces sont les plus demandés.",
        "",
        "5. Faire appel à un professionnel",
        "Un agent immobilier certifié vous accompagne dans toutes les étapes : recherche, visite, négociation et signature. Son expertise vous fait gagner du temps et de l'argent.",
        "",
        "Investir dans l'immobilier au Cameroun est une décision judicieuse à condition de bien se préparer. Keyora est là pour vous accompagner à chaque étape de votre projet.",
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
      category: 'Investissement',
      viewCount: 4521,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-02-20'),
      authorId: superAdminId,
    },
    {
      title: 'Guide complet pour acheter votre première maison',
      slug: 'guide-complet-acheter-premiere-maison',
      excerpt: 'Vous souhaitez devenir propriétaire pour la première fois ? Suivez notre guide pas à pas pour réussir votre achat.',
      content: [
        'Devenir propriétaire est un rêve accessible. Voici un guide complet pour acheter votre première maison au Cameroun :',
        '',
        'Étape 1 : Définir votre budget',
        "Calculez votre capacité d'emprunt : vos mensualités ne doivent pas dépasser 35% de vos revenus mensuels. Prévoyez un apport personnel d'au moins 20% du prix du bien.",
        '',
        'Étape 2 : Rechercher le bien idéal',
        'Utilisez Keyora pour trouver des annonces correspondant à vos critères. Filtrez par ville, quartier, type de bien et budget. Consultez les photos et les descriptions détaillées.',
        '',
        'Étape 3 : Visiter et inspecter',
        "Ne vous fiez pas uniquement aux photos. Visitez toujours le bien en personne, vérifiez l'état général, la plomberie, l'électricité et l'absence d'humidité.",
        '',
        'Étape 4 : Négocier le prix',
        "Le prix affiché n'est pas toujours ferme. Préparez vos arguments : état du marché, travaux nécessaires, comparaison avec des biens similaires.",
        '',
        'Étape 5 : Signer l’acte de vente',
        "Faites appel à un notaire pour authentifier la vente. Vérifiez que le titre foncier est bien au nom du vendeur et qu'il n'y a pas d'hypothèque.",
        '',
        "Avec Keyora, trouvez la maison de vos rêves et réalisez votre projet d'achat en toute sérénité.",
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400&h=300&fit=crop',
      category: 'Guide Acheteur',
      viewCount: 6789,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-02-15'),
      authorId: superAdminId,
    },
    {
      title: "Les tendances de l'architecture moderne au Cameroun",
      slug: 'tendances-architecture-moderne',
      excerpt: "L'architecture contemporaine camerounaise évolue. Découvrez les styles et tendances qui façonnent nos villes.",
      content: [
        "L'architecture moderne au Cameroun connaît une véritable renaissance. Voici les tendances qui transforment nos villes :",
        '',
        'Style contemporain afro-minimaliste',
        'Les nouvelles constructions allient lignes épurées et matériaux locaux. Le bois, la pierre de taille et le bambou sont utilisés pour créer des espaces à la fois modernes et ancrés dans la tradition.',
        '',
        'Maisons intelligentes (smart homes)',
        "La domotique gagne du terrain : éclairage automatisé, climatisation connectée, systèmes de sécurité intelligents. Les propriétaires camerounais adoptent ces technologies pour plus de confort et d'économie d'énergie.",
        '',
        'Architecture bioclimatique',
        'Face aux enjeux climatiques, les architectes conçoivent des bâtiments qui tirent parti du climat : ventilation naturelle, orientation optimale, toitures végétalisées. Ces constructions réduisent la consommation énergétique de 30 à 50%.',
        '',
        'Espaces ouverts et modulables',
        "Les cloisons cèdent la place aux espaces ouverts. Le salon, la salle à manger et la cuisine ne forment plus qu'un seul espace de vie, plus convivial et lumineux.",
        '',
        'Matériaux éco-responsables',
        'Le parpaing traditionnel est progressivement remplacé par des matériaux plus durables : briques en terre cuite, béton cellulaire, panneaux solaires intégrés.',
        '',
        "L'architecture camerounaise moderne reflète notre identité tout en s'ouvrant aux innovations mondiales.",
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=400&h=300&fit=crop',
      category: 'Architecture',
      viewCount: 3102,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-02-10'),
      authorId: superAdminId,
    },
    {
      title: 'Louer ou acheter au Cameroun : que choisir ?',
      slug: 'louer-ou-acheter-cameroun',
      excerpt: "Face à l'évolution du marché immobilier, la question se pose : vaut-il mieux louer ou acheter ? Analyse complète.",
      content: [
        "Une question revient sans cesse : faut-il louer ou acheter ? Voici une analyse détaillée pour vous aider à prendre la bonne décision.",
        '',
        'Avantages de la location',
        '- Flexibilité : vous pouvez déménager facilement selon vos besoins professionnels ou familiaux',
        "- Pas d'entretien coûteux : le propriétaire prend en charge les réparations",
        "- Investissement initial faible : pas d'apport personnel requis",
        "- Idéal pour les séjours de courte durée (moins de 3 ans)",
        '',
        "Avantages de l'achat",
        "- Constitution d'un patrimoine : chaque mensualité rembourse votre crédit",
        '- Liberté : vous faites les travaux et aménagements que vous souhaitez',
        "- Plus-value potentielle : l'immobilier camerounais prend en moyenne 5 à 8% par an",
        '- Revenus locatifs : vous pouvez louer votre bien si vous déménagez',
        '',
        'Quand acheter ?',
        "- Vous avez un apport d'au moins 20%",
        '- Vous comptez rester dans la même ville plus de 5 ans',
        '- Les taux de crédit sont attractifs (actuellement 8-10%)',
        "- Vous voulez vous constituer un patrimoine pour votre retraite",
        '',
        'Quand louer ?',
        '- Vous venez de commencer votre carrière',
        '- Vous changez fréquemment de ville',
        "- Vous n'avez pas encore d'apport personnel suffisant",
        "- Les prix dans votre quartier cible sont trop élevés",
        '',
        'Chez Keyora, nous vous accompagnons dans votre réflexion pour faire le choix le plus adapté à votre situation.',
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop',
      category: 'Conseils',
      viewCount: 5234,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-02-05'),
      authorId: superAdminId,
    },
    {
      title: 'Décoration intérieure : les styles qui subliment votre bien',
      slug: 'decoration-interieure-styles',
      excerpt: 'Une décoration soignée augmente la valeur perçue de votre bien. Découvrez les styles tendances au Cameroun.',
      content: [
        'La décoration intérieure transforme un simple logement en un véritable foyer. Voici les styles qui ont la cote au Cameroun :',
        '',
        'Style afro-chic',
        'Ce style mélange mobilier contemporain et pièces artisanales africaines. Tapis traditionnels, sculptures en bois, tissus wax et poteries créent une atmosphère chaleureuse et authentique. Les couleurs chaudes (ocre, terre cuite, vert forêt) dominent.',
        '',
        'Style scandinave tropical',
        'Le minimalisme scandinave revisité aux couleurs des tropiques. Murs blancs, bois clair, plantes vertes abondantes et touches de couleurs vives (jaune, bleu canard). Parfait pour les petits espaces.',
        '',
        'Style industriel doux',
        "Inspiré des lofts new-yorkais, ce style utilise le béton ciré, la brique apparente et le métal noir, adoucis par des textiles naturels (lin, coton) et un éclairage chaleureux.",
        '',
        'Conseils pour valoriser votre bien',
        "- Misez sur un éclairage en couches : plafonnier, lampes sur pied, lumières d'accentuation",
        '- Utilisez des miroirs pour agrandir visuellement les pièces',
        '- Choisissez des couleurs neutres pour les murs (beige, blanc cassé, gris clair)',
        "- Ajoutez des plantes vertes : elles purifient l'air et apportent de la vie",
        '',
        'Un bien bien décoré se vend ou se loue plus vite et à un meilleur prix. Keyora vous conseille pour valoriser votre propriété.',
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1565182999555-022f8953b5b6?w=400&h=300&fit=crop',
      category: 'Décoration',
      viewCount: 2876,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-01-30'),
      authorId: superAdminId,
    },
    {
      title: 'Comprendre le titre foncier au Cameroun',
      slug: 'comprendre-titre-foncier-cameroun',
      excerpt: 'Le titre foncier est le document le plus important pour sécuriser votre propriété. Tout ce que vous devez savoir.',
      content: [
        'Le titre foncier est le document juridique qui établit votre droit de propriété sur un terrain ou un immeuble au Cameroun. Voici ce qu’il faut absolument savoir :',
        '',
        "Qu'est-ce qu'un titre foncier ?",
        "C'est un document officiel délivré par le Conservateur Foncier qui atteste que vous êtes le propriétaire légitime d'un bien. Il contient : le numéro de titre, la superficie, la localisation, les limites du terrain et le nom du propriétaire.",
        '',
        "Comment l'obtenir ?",
        'La procédure comporte plusieurs étapes :',
        "1. Dépôt d'une demande au Service des Domaines",
        '2. Bornage du terrain par un géomètre agréé',
        '3. Enquête de commodo et incommodo (vérification des voisins)',
        '4. Publicité légale (insertion dans un journal)',
        '5. Délivrance du titre foncier par le Conservateur',
        '',
        'Pourquoi est-ce crucial ?',
        "- Sans titre foncier, vous ne pouvez pas vendre officiellement le bien",
        '- Les banques exigent un titre foncier pour accorder un crédit hypothécaire',
        "- En cas de litige, seul le titulaire du titre foncier est protégé",
        "- Le titre foncier vous protège contre les expropriations abusives",
        '',
        "Pièges à éviter",
        '- Méfiez-vous des "papiers maison" qui ne sont pas des titres fonciers',
        "- Vérifiez toujours l'authenticité du titre auprès du Conservatoire",
        "- Ne signez jamais d'acte sans avoir vu le titre foncier original",
        '- Faites appel à un notaire pour toutes les transactions',
        '',
        "La sécurisation foncière est la clé d'un investissement immobilier réussi. Keyora vous met en relation avec des professionnels de confiance.",
      ].join('\n'),
      coverUrl: 'https://images.unsplash.com/photo-1560870861-8c5348e8aa12?w=400&h=300&fit=crop',
      category: 'Juridique',
      viewCount: 7891,
      status: PostStatus.PUBLISHED,
      publishedAt: new Date('2024-01-25'),
      authorId: superAdminId,
    },
  ];
}

async function main() {
  console.log('Seeding...');

  await prisma.listingPhoto.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.blogPost.deleteMany();
  await prisma.supportRequest.deleteMany();
  await prisma.user.deleteMany();

  const superAdminPassword = await bcrypt.hash('SuperAdmin123!', 10);
  const modoPassword = await bcrypt.hash('Modo123!', 10);
  const sellerPassword = await bcrypt.hash('Vendeur123!', 10);

  const superAdmin = await prisma.user.create({
    data: {
      email: 'superadmin@keyora.com',
      passwordHash: superAdminPassword,
      fullName: 'Sandrine Biya',
      role: Role.SUPERADMIN,
      phone: '+237671234567',
      isVerified: true,
    },
  });

  const moderator = await prisma.user.create({
    data: {
      email: 'moderateur@keyora.com',
      passwordHash: modoPassword,
      fullName: 'Modérateur Keyora',
      role: Role.MODERATOR,
      phone: '+237672345678',
      isVerified: true,
    },
  });

  const thierry = await prisma.user.create({
    data: {
      email: 'thierry@keyora.com',
      passwordHash: sellerPassword,
      fullName: 'Thierry Kamga',
      role: Role.SELLER,
      phone: '+237677112233',
      isVerified: true,
    },
  });

  const ludovic = await prisma.user.create({
    data: {
      email: 'ludovic@keyora.com',
      passwordHash: sellerPassword,
      fullName: 'Ludovic Nguemo',
      role: Role.SELLER,
      phone: '+237677445566',
      isVerified: true,
    },
  });

  const salam = await prisma.user.create({
    data: {
      email: 'salam@keyora.com',
      passwordHash: sellerPassword,
      fullName: 'Salam Ousmane',
      role: Role.SELLER,
      phone: '+237677778899',
      isVerified: true,
    },
  });

  await prisma.blogPost.createMany({ data: getBlogs(superAdmin.id) });

  const listingsData = [
    {
      title: 'Villa de prestige avec piscine - Bastos',
      description: 'Somptueuse villa duplex neuve située dans le quartier sécurisé et diplomatique de Bastos. Finitions haut de gamme, grand jardin arboré, piscine à débordement, 5 chambres autonomes, vaste salon de réception et dépendance pour le personnel.',
      type: ListingType.SALE,
      propertyType: PropertyType.HOUSE,
      price: 280000000,
      area: 350,
      rooms: 7,
      bedrooms: 5,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 4,
      address: 'Rue de la Résidence',
      city: 'Yaoundé',
      latitude: 3.8854,
      longitude: 11.5165,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: thierry.id,
      photos: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    },
    {
      title: 'Appartement chic meublé de standing - Bonapriso',
      description: 'Appartement entièrement meublé et équipé dans une résidence calme à Bonapriso. Climatisation centrale, groupe électrogène, forage, sécurité H24. Proche des restaurants et supermarchés.',
      type: ListingType.RENT,
      propertyType: PropertyType.APARTMENT,
      price: 650000,
      area: 140,
      rooms: 4,
      bedrooms: 3,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 2,
      address: 'Rue Njo-Njo',
      city: 'Douala',
      latitude: 4.0298,
      longitude: 9.6974,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: thierry.id,
      photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    },
    {
      title: 'Terrain titré constructible - Odza',
      description: 'Très beau terrain plat de 600m² situé dans la zone résidentielle d\'Odza. Accès facile, électricité et eau disponibles. Parfait pour une villa familiale ou un petit projet d\'immeuble de rapport. Titre foncier individuel disponible immédiatement.',
      type: ListingType.SALE,
      propertyType: PropertyType.LAND,
      price: 25000000,
      area: 600,
      address: 'Odza Petit Marché',
      city: 'Yaoundé',
      latitude: 3.8182,
      longitude: 11.5312,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: thierry.id,
      photos: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    },
    {
      title: 'Local commercial spacieux - Centre-ville',
      description: 'Vaste local de 180m² idéal pour bureaux ou showroom en plein cœur de Yaoundé. Vitrine sur rue passante, parking privé, sanitaires et climatisation pré-installée.',
      type: ListingType.RENT,
      propertyType: PropertyType.COMMERCIAL,
      price: 1200000,
      area: 180,
      rooms: 6,
      bathrooms: 2,
      address: 'Avenue Kennedy',
      city: 'Yaoundé',
      latitude: 3.8633,
      longitude: 11.5199,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: thierry.id,
      photos: ['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800'],
    },
    {
      title: 'Maison contemporaine - Kotto',
      description: 'Maison moderne de 4 chambres dans une barrière sécurisée à Kotto. Salon lumineux, cuisine moderne, cour pavée pouvant accueillir 3 voitures.',
      type: ListingType.SALE,
      propertyType: PropertyType.HOUSE,
      price: 75000000,
      area: 200,
      rooms: 5,
      bedrooms: 4,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 3,
      address: 'Kotto Bloc L',
      city: 'Douala',
      latitude: 4.0901,
      longitude: 9.7712,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: thierry.id,
      photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800'],
    },
    {
      title: 'Studio moderne meublé - Ngoa-Ekelle',
      description: 'Studio entièrement équipé et meublé avec goût à Ngoa-Ekelle, à 5 minutes des universités. Lit double, kitchenette équipée, TV, connexion Wi-Fi, balcon privé. Idéal étudiant ou jeune professionnel.',
      type: ListingType.RENT,
      propertyType: PropertyType.APARTMENT,
      price: 85000,
      area: 45,
      rooms: 2,
      bedrooms: 1,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 1,
      address: 'Avenue de l\'Université',
      city: 'Yaoundé',
      latitude: 3.8612,
      longitude: 11.5015,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: ludovic.id,
      photos: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'],
    },
    {
      title: 'Villa de vacances les pieds dans l\'eau - Kribi',
      description: 'Superbe villa avec accès direct à la plage de sable fin de Kribi. 3 grandes suites, grand salon avec vue sur l\'océan, terrasse aménagée et service de conciergerie inclus. Parfait pour les vacances ou week-ends.',
      type: ListingType.RENT,
      propertyType: PropertyType.HOUSE,
      price: 1500000,
      area: 250,
      rooms: 5,
      bedrooms: 3,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 3,
      address: 'Route de Mboro',
      city: 'Kribi',
      latitude: 2.9377,
      longitude: 9.9076,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: ludovic.id,
      photos: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800'],
    },
    {
      title: 'Terrain agricole fertile - Obala',
      description: 'Vaste terrain agricole de 5000m² situé en périphérie d\'Obala. Sol riche, idéal pour maraîchage, plantation de cacao ou d\'arbres fruitiers. Accès direct par piste praticable.',
      type: ListingType.SALE,
      propertyType: PropertyType.LAND,
      price: 18000000,
      area: 5000,
      address: 'Entrée Sud Obala',
      city: 'Obala',
      latitude: 4.1678,
      longitude: 11.5332,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: ludovic.id,
      photos: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800'],
    },
    {
      title: 'Duplex contemporain luxueux - Santa Barbara',
      description: 'Magnifique duplex moderne de 5 chambres situé dans le quartier huppé de Santa Barbara. Prestations haut de gamme, cuisine italienne, garage fermé 2 voitures, dépendances.',
      type: ListingType.SALE,
      propertyType: PropertyType.HOUSE,
      price: 150000000,
      area: 300,
      rooms: 6,
      bedrooms: 5,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 4,
      address: 'Avenue de la Paix',
      city: 'Yaoundé',
      latitude: 3.9056,
      longitude: 11.5302,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: ludovic.id,
      photos: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800'],
    },
    {
      title: 'Bel appartement familial - Bonamoussadi',
      description: 'Appartement propre et spacieux au 2ème étage d\'un immeuble résidentiel sécurisé à Bonamoussadi. Grand séjour, balcons, cuisine avec buanderie.',
      type: ListingType.RENT,
      propertyType: PropertyType.APARTMENT,
      price: 280000,
      area: 110,
      rooms: 4,
      bedrooms: 3,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 2,
      address: 'Rue des Palmiers',
      city: 'Douala',
      latitude: 4.0733,
      longitude: 9.7554,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: ludovic.id,
      photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    },
    {
      title: 'Appartement contemporain design - Akwa',
      description: 'Appartement de standing avec finitions soignées en plein cœur d\'Akwa. Lumineux, climatisé, ascenseur, surveillance vidéo, parking souterrain.',
      type: ListingType.RENT,
      propertyType: PropertyType.APARTMENT,
      price: 350000,
      area: 120,
      rooms: 4,
      bedrooms: 2,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 2,
      address: 'Rue Castelnau',
      city: 'Douala',
      latitude: 4.0507,
      longitude: 9.7085,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: salam.id,
      photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    },
    {
      title: 'Loft meublé de luxe - Bastos',
      description: 'Superbe loft en duplex meublé dans un style industriel contemporain. Idéal pour expatriés ou séjours d\'affaires. Internet fibre optique, ménage inclus.',
      type: ListingType.RENT,
      propertyType: PropertyType.APARTMENT,
      price: 800000,
      area: 90,
      rooms: 3,
      bedrooms: 1,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 1,
      address: 'Rue de la Cascade',
      city: 'Yaoundé',
      latitude: 3.8899,
      longitude: 11.5188,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: salam.id,
      photos: ['https://images.unsplash.com/photo-1502672017483-7c8a6c25118c?w=800'],
    },
    {
      title: 'Terrain commercial en bordure de route - Limbe',
      description: 'Opportunité rare : terrain de 1200m² en bordure d\'axe routier principal à Limbe. Parfait pour hôtel, supermarché ou station-service. Vue mer partielle, entièrement plat.',
      type: ListingType.SALE,
      propertyType: PropertyType.LAND,
      price: 65000000,
      area: 1200,
      address: 'Coastal Highway',
      city: 'Limbe',
      latitude: 4.0167,
      longitude: 9.2167,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: salam.id,
      photos: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    },
    {
      title: 'Villa duplex contemporaine - Logbessou',
      description: 'Grande villa de 6 pièces neuve à Logbessou. 4 chambres spacieuses, 3 douches, grand salon, cuisine spacieuse, jardin, barrière avec portail automatique.',
      type: ListingType.SALE,
      propertyType: PropertyType.HOUSE,
      price: 85000000,
      area: 280,
      rooms: 6,
      bedrooms: 4,
      livingRoom: 1,
      kitchen: 1,
      bathrooms: 3,
      address: 'Logbessou Entrée Chefferie',
      city: 'Douala',
      latitude: 4.0855,
      longitude: 9.7891,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: salam.id,
      photos: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800'],
    },
    {
      title: 'Bureaux professionnels modernes - Akwa',
      description: 'Étage complet de bureaux cloisonnés de 250m² à louer. Très bien situé sur axe commercial majeur d\'Akwa. Idéal agence, cabinet médical ou siège social.',
      type: ListingType.RENT,
      propertyType: PropertyType.COMMERCIAL,
      price: 2000000,
      area: 250,
      rooms: 8,
      bathrooms: 3,
      address: 'Boulevard de la Liberté',
      city: 'Douala',
      latitude: 4.0488,
      longitude: 9.6991,
      status: ListingStatus.PUBLISHED,
      publishedAt: new Date(),
      ownerId: salam.id,
      photos: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
    },
  ];

  for (const item of listingsData) {
    const { photos, ...listingFields } = item;
    await prisma.listing.create({
      data: {
        ...listingFields,
        photos: {
          create: photos.map((url, index) => ({ url, position: index })),
        },
      },
    });
  }

  console.log('Seed completed!');
  console.log('Super Admin: superadmin@keyora.com / SuperAdmin123!');
  console.log('Moderator: moderateur@keyora.com / Modo123!');
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());